import { useState } from "react";
import { Apple, CalendarDays, Clock3, MapPin, Plus, Share2, Star, Trash2, Upload, UserRound } from "lucide-react";
import "../../styles/barbero/perfil-barberia-barbero.css";
import BarberoModal from "./barbero-modal";

const serviciosIniciales = [
  { nombre: "Masaje", precio: "$150", imagen: "https://images.unsplash.com/photo-1503951914875-452162b0f3f1?auto=format&fit=crop&w=300&q=80" },
  { nombre: "Diseño personalizado", precio: "$150", imagen: "https://images.unsplash.com/photo-1622286342621-4bd786c2447c?auto=format&fit=crop&w=300&q=80" },
  { nombre: "Corte de cejas", precio: "$150", imagen: "https://images.unsplash.com/photo-1512690459411-b9245aed614b?auto=format&fit=crop&w=300&q=80" },
  { nombre: "Corte de cabello", precio: "$150", imagen: "https://images.unsplash.com/photo-1517832606299-7ae9b720a186?auto=format&fit=crop&w=300&q=80" },
];
const dias = ["Lunes", "Martes", "Miércoles", "Jueves", "Sábado", "Domingo"];

export default function PerfilBarberiaBarbero() {
  const [servicios, setServicios] = useState(serviciosIniciales);
  const [modal, setModal] = useState("");
  const [nombreServicio, setNombreServicio] = useState("");
  const [horarios, setHorarios] = useState(Object.fromEntries(dias.map((dia) => [dia, "12:00 PM - 3:00 PM"])));
  const guardarServicio = (event) => { event.preventDefault(); if (!nombreServicio.trim()) return; setServicios((actual) => [...actual, { nombre: nombreServicio, precio: "$150", imagen: serviciosIniciales[0].imagen }]); setNombreServicio(""); setModal("guardado"); };

  return <section className="bp-page">
    <header className="bp-heading"><div><p>Panel barbero</p><h2>Perfil barbería</h2><span>Administra la información visible para tus clientes.</span></div><button type="button" onClick={() => setModal("guardar")}>Guardar cambios</button></header>
    <div className="bp-grid">
      <aside className="bp-profile-card"><div className="bp-cover" /><div className="bp-avatar"><UserRound size={58} /></div><h3>Mathew McCoy · Barbería profesional</h3><span><MapPin size={13} /> Main St, Las Vegas (2 mi)</span><p><Star size={13} fill="currentColor" /> 5.0 (24)</p><div className="bp-quick"><button type="button" onClick={() => setModal("mapa")}><MapPin size={16} /> Mapa</button><button type="button" onClick={() => setModal("chat")}><Apple size={16} /> Chat</button><button type="button" onClick={() => setModal("compartir")}><Share2 size={16} /> Compartir</button></div><h4>Localización</h4><div className="bp-address"><MapPin size={16} /> 3799 S Las Vegas Blvd, Las Vegas, NV 89109</div><iframe title="Ubicación de la barbería" className="bp-map" src="https://maps.google.com/maps?q=3799%20S%20Las%20Vegas%20Blvd%2C%20Las%20Vegas&t=&z=13&ie=UTF8&iwloc=&output=embed" loading="lazy" /></aside>
      <main className="bp-about"><nav><button className="active">Acerca</button><button>Servicios</button><button>Reseñas</button></nav><p className="bp-description">Somos una barbería con mucha experiencia en cortes, barba y tratamientos. <button type="button">Leer más…</button></p><h4>Horario de atención</h4><dl className="bp-hours"><div><dt>Lunes - Viernes</dt><dd>09:00 am - 08:00 pm</dd></div><div><dt>Sábado - Domingo</dt><dd>09:00 am - 09:00 pm</dd></div></dl><h4>Habilidades</h4><div className="bp-services">{servicios.map((servicio, index) => <article key={`${servicio.nombre}-${index}`}><img src={servicio.imagen} alt={servicio.nombre} /><strong>{servicio.nombre}</strong><span><Star size={11} fill="currentColor" /> 4.8</span><b>{servicio.precio}</b></article>)}</div><button type="button" className="bp-save" onClick={() => setModal("guardar")}>Guardar</button></main>
      <section className="bp-settings"><div className="bp-stat"><div><span>Experiencia</span><strong>5 años</strong></div><div><span>Servicios/clientes</span><strong>342 clientes</strong></div><div><span>Puntuación</span><strong><Star size={12} fill="currentColor" /> 5.0</strong></div></div><div className="bp-setting-tabs"><button><Clock3 size={21} />Horario disponible</button><button><CalendarDays size={21} />Fechas importantes</button></div><div className="bp-day-pills">{["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"].map((dia) => <button key={dia}>{dia}</button>)}</div><div className="bp-schedule">{dias.map((dia) => <div key={dia}><span>{dia}</span><button type="button" onClick={() => setModal(`horario-${dia}`)}>{horarios[dia]}</button><button className="bp-circle" type="button" onClick={() => setModal(`horario-${dia}`)}><Plus size={15} /></button><button className="bp-trash" type="button" onClick={() => setHorarios((actual) => ({ ...actual, [dia]: "Sin horario" }))}><Trash2 size={14} /></button></div>)}</div></section>
      <aside className="bp-service-form"><div className="bp-form-title"><h3>Políticas de cancelación</h3><label><input type="checkbox" defaultChecked /> Flexible <small>(2 días · 50% refund)</small></label><label><input type="checkbox" defaultChecked /> Moderate <small>(7 días · 50% refund)</small></label><label><input type="checkbox" defaultChecked /> Strict <small>(14 días · 50% refund)</small></label></div><button type="button" className="bp-upload" onClick={() => setModal("imagen")}><Upload size={20} /> Subir imagen <small>Support: JPG, PNG, JPEG</small></button><form onSubmit={guardarServicio}><label>Seleccionar servicio<select defaultValue=""><option value="" disabled>Seleccionar servicio</option><option>Corte</option><option>Barba</option></select></label><div><input placeholder="Precio $" /><input placeholder="Servicio en físico" /></div><textarea placeholder="Descripción del servicio" /><button className="bp-save" type="submit">Guardar</button></form></aside>
    </div>
    <BarberoModal open={modal === "imagen"} title="Subir imagen" onClose={() => setModal("")} footer={<button className="bm-primary" onClick={() => setModal("guardado")}>Subir</button>}><p>Selecciona una fotografía para mostrarla en tu perfil. La carga será temporal hasta conectar el almacenamiento.</p><input type="file" accept="image/*" /></BarberoModal>
    <BarberoModal open={modal.startsWith("horario-")} title="Editar horario" onClose={() => setModal("")} footer={<button className="bm-primary" onClick={() => setModal("guardado")}>Guardar horario</button>}><p>Configura el horario para {modal.replace("horario-", "")}.</p><input className="bp-modal-input" defaultValue="12:00 PM - 3:00 PM" /></BarberoModal>
    <BarberoModal open={modal === "mapa"} title="Ubicación" onClose={() => setModal("")} footer={<button className="bm-primary" onClick={() => setModal("")}>Cerrar</button>}><p>3799 S Las Vegas Blvd, Las Vegas, NV 89109</p></BarberoModal>
    <BarberoModal open={modal === "chat"} title="Chat de barbería" onClose={() => setModal("")} footer={<button className="bm-primary" onClick={() => setModal("")}>Enviar</button>}><textarea className="bp-modal-input" placeholder="Escribe un mensaje…" /></BarberoModal>
    <BarberoModal open={modal === "compartir"} title="Compartir perfil" onClose={() => setModal("")} footer={<button className="bm-primary" onClick={() => setModal("")}>Copiar enlace</button>}><p>Comparte tu perfil de Barber Hub con tus clientes.</p></BarberoModal>
    <BarberoModal open={modal === "guardar" || modal === "guardado"} title={modal === "guardar" ? "Guardar cambios" : "Cambios guardados"} onClose={() => setModal("")} footer={<button className="bm-primary" onClick={() => setModal("")}>{modal === "guardar" ? "Confirmar" : "Continuar"}</button>}><p>{modal === "guardar" ? "Los cambios se guardarán temporalmente en esta sesión." : "La interfaz se actualizó. El guardado permanente llegará con el backend."}</p></BarberoModal>
  </section>;
}
