-- Antes, Estado > Ciudad > Zona vivía como un objeto fijo en
-- frontend/src/modules/cliente/data/ubicaciones.js — para que el super admin pueda
-- agregar ciudades/zonas desde un panel real, se mueve a la base. Los estados se
-- quedan fijos en el frontend (son los 32 de México, no cambian); solo ciudad y zona
-- se vuelven administrables.
create table if not exists public.ciudades (
  id uuid primary key default gen_random_uuid(),
  estado text not null,
  ciudad text not null,
  created_at timestamptz not null default now(),
  unique (estado, ciudad)
);

create table if not exists public.zonas (
  id uuid primary key default gen_random_uuid(),
  ciudad_id uuid not null references public.ciudades(id) on delete cascade,
  zona text not null,
  created_at timestamptz not null default now(),
  unique (ciudad_id, zona)
);

alter table public.ciudades enable row level security;
alter table public.zonas enable row level security;

-- Lectura pública (lo usan Explorar y el registro de barbería, con o sin sesión).
-- Nada de escritura por RLS: se agregan solo por el backend con la llave de
-- servicio, desde el endpoint exclusivo de super admin.
create policy ciudades_read on public.ciudades for select using (true);
create policy zonas_read on public.zonas for select using (true);

grant select on public.ciudades to anon, authenticated;
grant select on public.zonas to anon, authenticated;

-- Seed: datos que ya existían en frontend/src/modules/cliente/data/ubicaciones.js,
-- migrados a la base para que el super admin pueda seguir agregando desde el panel.
insert into public.ciudades (estado, ciudad) values
  ('Aguascalientes', 'Aguascalientes'),
  ('Aguascalientes', 'Jesús María'),
  ('Aguascalientes', 'Calvillo'),
  ('Baja California', 'Tijuana'),
  ('Baja California', 'Mexicali'),
  ('Baja California', 'Ensenada'),
  ('Baja California', 'Rosarito'),
  ('Baja California Sur', 'La Paz'),
  ('Baja California Sur', 'Los Cabos'),
  ('Baja California Sur', 'Loreto'),
  ('Campeche', 'Campeche'),
  ('Campeche', 'Ciudad del Carmen'),
  ('Chiapas', 'Tuxtla Gutiérrez'),
  ('Chiapas', 'San Cristóbal de las Casas'),
  ('Chiapas', 'Tapachula'),
  ('Chihuahua', 'Chihuahua'),
  ('Chihuahua', 'Ciudad Juárez'),
  ('Chihuahua', 'Cuauhtémoc'),
  ('Ciudad de México', 'CDMX'),
  ('Coahuila', 'Saltillo'),
  ('Coahuila', 'Torreón'),
  ('Coahuila', 'Monclova'),
  ('Coahuila', 'Piedras Negras'),
  ('Colima', 'Colima'),
  ('Colima', 'Manzanillo'),
  ('Colima', 'Villa de Álvarez'),
  ('Durango', 'Durango'),
  ('Durango', 'Gómez Palacio'),
  ('Durango', 'Lerdo'),
  ('Estado de México', 'Toluca'),
  ('Estado de México', 'Naucalpan'),
  ('Estado de México', 'Ecatepec'),
  ('Estado de México', 'Tlalnepantla'),
  ('Estado de México', 'Nezahualcóyotl'),
  ('Estado de México', 'Metepec'),
  ('Estado de México', 'Cuautitlán Izcalli'),
  ('Estado de México', 'Atizapán de Zaragoza'),
  ('Estado de México', 'Huixquilucan'),
  ('Guanajuato', 'León'),
  ('Guanajuato', 'Guanajuato'),
  ('Guanajuato', 'Irapuato'),
  ('Guanajuato', 'Celaya'),
  ('Guanajuato', 'Salamanca'),
  ('Guerrero', 'Acapulco'),
  ('Guerrero', 'Chilpancingo'),
  ('Guerrero', 'Iguala'),
  ('Guerrero', 'Zihuatanejo'),
  ('Hidalgo', 'Pachuca'),
  ('Hidalgo', 'Tulancingo'),
  ('Hidalgo', 'Tizayuca'),
  ('Jalisco', 'Guadalajara'),
  ('Jalisco', 'Zapopan'),
  ('Jalisco', 'Puerto Vallarta'),
  ('Jalisco', 'Tlaquepaque'),
  ('Jalisco', 'Tonalá'),
  ('Jalisco', 'Tlajomulco de Zúñiga'),
  ('Michoacán', 'Morelia'),
  ('Michoacán', 'Uruapan'),
  ('Michoacán', 'Zamora'),
  ('Morelos', 'Cuernavaca'),
  ('Morelos', 'Jiutepec'),
  ('Morelos', 'Cuautla'),
  ('Nayarit', 'Tepic'),
  ('Nayarit', 'Bahía de Banderas'),
  ('Nuevo León', 'Monterrey'),
  ('Nuevo León', 'San Nicolás de los Garza'),
  ('Nuevo León', 'Guadalupe'),
  ('Nuevo León', 'Apodaca'),
  ('Nuevo León', 'Santa Catarina'),
  ('Nuevo León', 'San Pedro Garza García'),
  ('Oaxaca', 'Oaxaca de Juárez'),
  ('Oaxaca', 'Salina Cruz'),
  ('Oaxaca', 'Huajuapan de León'),
  ('Puebla', 'Puebla'),
  ('Puebla', 'Tehuacán'),
  ('Puebla', 'San Andrés Cholula'),
  ('Puebla', 'Atlixco'),
  ('Querétaro', 'Querétaro'),
  ('Querétaro', 'San Juan del Río'),
  ('Querétaro', 'Corregidora'),
  ('Quintana Roo', 'Cancún'),
  ('Quintana Roo', 'Playa del Carmen'),
  ('Quintana Roo', 'Chetumal'),
  ('Quintana Roo', 'Tulum'),
  ('San Luis Potosí', 'San Luis Potosí'),
  ('San Luis Potosí', 'Soledad de Graciano Sánchez'),
  ('Sinaloa', 'Culiacán'),
  ('Sinaloa', 'Mazatlán'),
  ('Sinaloa', 'Los Mochis'),
  ('Sonora', 'Hermosillo'),
  ('Sonora', 'Ciudad Obregón'),
  ('Sonora', 'Nogales'),
  ('Sonora', 'San Luis Río Colorado'),
  ('Tabasco', 'Villahermosa'),
  ('Tabasco', 'Cárdenas'),
  ('Tamaulipas', 'Reynosa'),
  ('Tamaulipas', 'Tampico'),
  ('Tamaulipas', 'Nuevo Laredo'),
  ('Tamaulipas', 'Matamoros'),
  ('Tamaulipas', 'Ciudad Victoria'),
  ('Tlaxcala', 'Tlaxcala'),
  ('Tlaxcala', 'Apizaco'),
  ('Tlaxcala', 'Huamantla'),
  ('Veracruz', 'Veracruz'),
  ('Veracruz', 'Xalapa'),
  ('Veracruz', 'Coatzacoalcos'),
  ('Veracruz', 'Córdoba'),
  ('Veracruz', 'Poza Rica'),
  ('Veracruz', 'Orizaba'),
  ('Yucatán', 'Mérida'),
  ('Yucatán', 'Valladolid'),
  ('Yucatán', 'Progreso'),
  ('Zacatecas', 'Zacatecas'),
  ('Zacatecas', 'Fresnillo')
on conflict (estado, ciudad) do nothing;

insert into public.zonas (ciudad_id, zona)
select c.id, v.zona
from (values
  ('Aguascalientes', 'Aguascalientes', 'Centro'),
  ('Aguascalientes', 'Aguascalientes', 'Bosques del Prado'),
  ('Aguascalientes', 'Aguascalientes', 'Las Américas'),
  ('Aguascalientes', 'Aguascalientes', 'Jardines de la Concepción'),
  ('Aguascalientes', 'Aguascalientes', 'Pulgas Pandas'),
  ('Aguascalientes', 'Jesús María', 'Centro'),
  ('Aguascalientes', 'Jesús María', 'Los Arcos'),
  ('Aguascalientes', 'Calvillo', 'Centro'),
  ('Baja California', 'Tijuana', 'Centro'),
  ('Baja California', 'Tijuana', 'Zona Río'),
  ('Baja California', 'Tijuana', 'Playas de Tijuana'),
  ('Baja California', 'Tijuana', 'Otay'),
  ('Baja California', 'Tijuana', 'Chapultepec'),
  ('Baja California', 'Tijuana', 'La Mesa'),
  ('Baja California', 'Mexicali', 'Centro'),
  ('Baja California', 'Mexicali', 'Nuevo Mexicali'),
  ('Baja California', 'Mexicali', 'Los Pinos'),
  ('Baja California', 'Mexicali', 'Estación Delta'),
  ('Baja California', 'Ensenada', 'Centro'),
  ('Baja California', 'Ensenada', 'Chapultepec'),
  ('Baja California', 'Ensenada', 'Valle Dorado'),
  ('Baja California', 'Rosarito', 'Centro'),
  ('Baja California', 'Rosarito', 'Costa Azul'),
  ('Baja California Sur', 'La Paz', 'Centro'),
  ('Baja California Sur', 'La Paz', 'El Mogote'),
  ('Baja California Sur', 'La Paz', 'Fidepaz'),
  ('Baja California Sur', 'Los Cabos', 'Cabo San Lucas'),
  ('Baja California Sur', 'Los Cabos', 'San José del Cabo'),
  ('Baja California Sur', 'Los Cabos', 'Zona Hotelera'),
  ('Baja California Sur', 'Loreto', 'Centro'),
  ('Campeche', 'Campeche', 'Centro'),
  ('Campeche', 'Campeche', 'San Francisco'),
  ('Campeche', 'Campeche', 'Fovissste'),
  ('Campeche', 'Ciudad del Carmen', 'Centro'),
  ('Chiapas', 'Tuxtla Gutiérrez', 'Centro'),
  ('Chiapas', 'Tuxtla Gutiérrez', 'Las Palmas'),
  ('Chiapas', 'Tuxtla Gutiérrez', 'Terán'),
  ('Chiapas', 'Tuxtla Gutiérrez', 'Bonampak'),
  ('Chiapas', 'San Cristóbal de las Casas', 'Centro'),
  ('Chiapas', 'San Cristóbal de las Casas', 'Fray Bartolomé'),
  ('Chiapas', 'Tapachula', 'Centro'),
  ('Chihuahua', 'Chihuahua', 'Centro'),
  ('Chihuahua', 'Chihuahua', 'Zona Dorada'),
  ('Chihuahua', 'Chihuahua', 'San Felipe'),
  ('Chihuahua', 'Chihuahua', 'Campestre'),
  ('Chihuahua', 'Ciudad Juárez', 'Centro'),
  ('Chihuahua', 'Ciudad Juárez', 'Las Misiones'),
  ('Chihuahua', 'Ciudad Juárez', 'Campestre'),
  ('Chihuahua', 'Ciudad Juárez', 'Pronaf'),
  ('Chihuahua', 'Cuauhtémoc', 'Centro'),
  ('Ciudad de México', 'CDMX', 'Centro Histórico'),
  ('Ciudad de México', 'CDMX', 'Roma Norte'),
  ('Ciudad de México', 'CDMX', 'Roma Sur'),
  ('Ciudad de México', 'CDMX', 'Condesa'),
  ('Ciudad de México', 'CDMX', 'Polanco'),
  ('Ciudad de México', 'CDMX', 'Coyoacán'),
  ('Ciudad de México', 'CDMX', 'Del Valle'),
  ('Ciudad de México', 'CDMX', 'Narvarte'),
  ('Ciudad de México', 'CDMX', 'Santa Fe'),
  ('Ciudad de México', 'CDMX', 'Doctores'),
  ('Ciudad de México', 'CDMX', 'Escandón'),
  ('Ciudad de México', 'CDMX', 'San Ángel'),
  ('Ciudad de México', 'CDMX', 'Tlalpan Centro'),
  ('Ciudad de México', 'CDMX', 'Xochimilco Centro'),
  ('Ciudad de México', 'CDMX', 'Nápoles'),
  ('Ciudad de México', 'CDMX', 'Anzures'),
  ('Ciudad de México', 'CDMX', 'Portales'),
  ('Ciudad de México', 'CDMX', 'Iztapalapa Centro'),
  ('Ciudad de México', 'CDMX', 'Álvaro Obregón Centro'),
  ('Coahuila', 'Saltillo', 'Centro'),
  ('Coahuila', 'Saltillo', 'Las Culturas'),
  ('Coahuila', 'Saltillo', 'República'),
  ('Coahuila', 'Saltillo', 'Torreón de la Cañada'),
  ('Coahuila', 'Torreón', 'Centro'),
  ('Coahuila', 'Torreón', 'Las Fuentes'),
  ('Coahuila', 'Torreón', 'Campestre La Rosita'),
  ('Coahuila', 'Monclova', 'Centro'),
  ('Coahuila', 'Piedras Negras', 'Centro'),
  ('Colima', 'Colima', 'Centro'),
  ('Colima', 'Colima', 'Las Víboras'),
  ('Colima', 'Colima', 'Lomas de Circunvalación'),
  ('Colima', 'Manzanillo', 'Centro'),
  ('Colima', 'Manzanillo', 'Las Brisas'),
  ('Colima', 'Manzanillo', 'Salagua'),
  ('Colima', 'Villa de Álvarez', 'Centro'),
  ('Durango', 'Durango', 'Centro'),
  ('Durango', 'Durango', 'Guadalupe Victoria'),
  ('Durango', 'Durango', 'Jardines del Sol'),
  ('Durango', 'Gómez Palacio', 'Centro'),
  ('Durango', 'Lerdo', 'Centro'),
  ('Estado de México', 'Toluca', 'Centro'),
  ('Estado de México', 'Toluca', 'Metepec'),
  ('Estado de México', 'Toluca', 'Zinacantepec'),
  ('Estado de México', 'Toluca', 'San Mateo Oxtotitlán'),
  ('Estado de México', 'Naucalpan', 'Centro'),
  ('Estado de México', 'Naucalpan', 'Satélite'),
  ('Estado de México', 'Naucalpan', 'Echegaray'),
  ('Estado de México', 'Naucalpan', 'Lomas Verdes'),
  ('Estado de México', 'Ecatepec', 'Centro'),
  ('Estado de México', 'Ecatepec', 'Ciudad Azteca'),
  ('Estado de México', 'Ecatepec', 'Las Américas'),
  ('Estado de México', 'Tlalnepantla', 'Centro'),
  ('Estado de México', 'Tlalnepantla', 'Viveros'),
  ('Estado de México', 'Tlalnepantla', 'Valle Ceylán'),
  ('Estado de México', 'Nezahualcóyotl', 'Centro'),
  ('Estado de México', 'Nezahualcóyotl', 'Benito Juárez'),
  ('Estado de México', 'Metepec', 'Centro'),
  ('Estado de México', 'Metepec', 'San Salvador'),
  ('Estado de México', 'Cuautitlán Izcalli', 'Centro'),
  ('Estado de México', 'Cuautitlán Izcalli', 'Lomas de San Miguel'),
  ('Estado de México', 'Atizapán de Zaragoza', 'Centro'),
  ('Estado de México', 'Atizapán de Zaragoza', 'Lago de Guadalupe'),
  ('Estado de México', 'Huixquilucan', 'Interlomas'),
  ('Estado de México', 'Huixquilucan', 'Centro'),
  ('Guanajuato', 'León', 'Centro'),
  ('Guanajuato', 'León', 'Del Valle'),
  ('Guanajuato', 'León', 'Jardines del Moral'),
  ('Guanajuato', 'León', 'Las Palomas'),
  ('Guanajuato', 'León', 'Piletas'),
  ('Guanajuato', 'Guanajuato', 'Centro'),
  ('Guanajuato', 'Guanajuato', 'Marfil'),
  ('Guanajuato', 'Irapuato', 'Centro'),
  ('Guanajuato', 'Irapuato', 'Las Reynas'),
  ('Guanajuato', 'Celaya', 'Centro'),
  ('Guanajuato', 'Celaya', 'Villas de Irapuato'),
  ('Guanajuato', 'Salamanca', 'Centro'),
  ('Guerrero', 'Acapulco', 'Centro'),
  ('Guerrero', 'Acapulco', 'Diamante'),
  ('Guerrero', 'Acapulco', 'Costa Azul'),
  ('Guerrero', 'Acapulco', 'Progreso'),
  ('Guerrero', 'Chilpancingo', 'Centro'),
  ('Guerrero', 'Iguala', 'Centro'),
  ('Guerrero', 'Zihuatanejo', 'Centro'),
  ('Guerrero', 'Zihuatanejo', 'Ixtapa'),
  ('Hidalgo', 'Pachuca', 'Centro'),
  ('Hidalgo', 'Pachuca', 'Las Palmas'),
  ('Hidalgo', 'Pachuca', 'Fraccionamiento Los Pinos'),
  ('Hidalgo', 'Tulancingo', 'Centro'),
  ('Hidalgo', 'Tizayuca', 'Centro'),
  ('Jalisco', 'Guadalajara', 'Centro'),
  ('Jalisco', 'Guadalajara', 'Providencia'),
  ('Jalisco', 'Guadalajara', 'Chapultepec'),
  ('Jalisco', 'Guadalajara', 'Americana'),
  ('Jalisco', 'Guadalajara', 'Country Club'),
  ('Jalisco', 'Guadalajara', 'Colonia Moderna'),
  ('Jalisco', 'Zapopan', 'Centro'),
  ('Jalisco', 'Zapopan', 'Andares'),
  ('Jalisco', 'Zapopan', 'Ciudad Granja'),
  ('Jalisco', 'Zapopan', 'Puerta de Hierro'),
  ('Jalisco', 'Zapopan', 'Valle Real'),
  ('Jalisco', 'Puerto Vallarta', 'Centro'),
  ('Jalisco', 'Puerto Vallarta', 'Zona Hotelera'),
  ('Jalisco', 'Puerto Vallarta', 'Marina Vallarta'),
  ('Jalisco', 'Tlaquepaque', 'Centro'),
  ('Jalisco', 'Tlaquepaque', 'Las Juntas'),
  ('Jalisco', 'Tonalá', 'Centro'),
  ('Jalisco', 'Tlajomulco de Zúñiga', 'Centro'),
  ('Jalisco', 'Tlajomulco de Zúñiga', 'Chulavista'),
  ('Michoacán', 'Morelia', 'Centro'),
  ('Michoacán', 'Morelia', 'Felix Ireta'),
  ('Michoacán', 'Morelia', 'Las Américas'),
  ('Michoacán', 'Morelia', 'Chapultepec'),
  ('Michoacán', 'Uruapan', 'Centro'),
  ('Michoacán', 'Uruapan', 'Jardines del Real'),
  ('Michoacán', 'Zamora', 'Centro'),
  ('Morelos', 'Cuernavaca', 'Centro'),
  ('Morelos', 'Cuernavaca', 'Vista Hermosa'),
  ('Morelos', 'Cuernavaca', 'Delicias'),
  ('Morelos', 'Cuernavaca', 'Lomas de la Selva'),
  ('Morelos', 'Jiutepec', 'Centro'),
  ('Morelos', 'Cuautla', 'Centro'),
  ('Nayarit', 'Tepic', 'Centro'),
  ('Nayarit', 'Tepic', 'Fray Junípero Serra'),
  ('Nayarit', 'Bahía de Banderas', 'Nuevo Vallarta'),
  ('Nayarit', 'Bahía de Banderas', 'Bucerías'),
  ('Nuevo León', 'Monterrey', 'Centro'),
  ('Nuevo León', 'Monterrey', 'San Pedro Garza García'),
  ('Nuevo León', 'Monterrey', 'Cumbres'),
  ('Nuevo León', 'Monterrey', 'Contry'),
  ('Nuevo León', 'Monterrey', 'Del Valle'),
  ('Nuevo León', 'Monterrey', 'Mitras'),
  ('Nuevo León', 'San Nicolás de los Garza', 'Centro'),
  ('Nuevo León', 'San Nicolás de los Garza', 'La Fe'),
  ('Nuevo León', 'Guadalupe', 'Centro'),
  ('Nuevo León', 'Guadalupe', 'Valle Soleado'),
  ('Nuevo León', 'Apodaca', 'Centro'),
  ('Nuevo León', 'Santa Catarina', 'Centro'),
  ('Nuevo León', 'San Pedro Garza García', 'Valle Oriente'),
  ('Nuevo León', 'San Pedro Garza García', 'Del Valle'),
  ('Oaxaca', 'Oaxaca de Juárez', 'Centro'),
  ('Oaxaca', 'Oaxaca de Juárez', 'Reforma'),
  ('Oaxaca', 'Oaxaca de Juárez', 'Xochimilco'),
  ('Oaxaca', 'Salina Cruz', 'Centro'),
  ('Oaxaca', 'Huajuapan de León', 'Centro'),
  ('Puebla', 'Puebla', 'Centro'),
  ('Puebla', 'Puebla', 'Angelópolis'),
  ('Puebla', 'Puebla', 'La Paz'),
  ('Puebla', 'Puebla', 'Cholula'),
  ('Puebla', 'Puebla', 'Zavaleta'),
  ('Puebla', 'Puebla', 'Lomas de Angelópolis'),
  ('Puebla', 'Puebla', 'San Manuel'),
  ('Puebla', 'Tehuacán', 'Centro'),
  ('Puebla', 'Tehuacán', 'La Huerta'),
  ('Puebla', 'San Andrés Cholula', 'Centro'),
  ('Puebla', 'San Andrés Cholula', 'Lomas de Angelópolis'),
  ('Puebla', 'Atlixco', 'Centro'),
  ('Querétaro', 'Querétaro', 'Centro'),
  ('Querétaro', 'Querétaro', 'Juriquilla'),
  ('Querétaro', 'Querétaro', 'Zibatá'),
  ('Querétaro', 'Querétaro', 'El Refugio'),
  ('Querétaro', 'Querétaro', 'Milenio III'),
  ('Querétaro', 'San Juan del Río', 'Centro'),
  ('Querétaro', 'Corregidora', 'Centro'),
  ('Quintana Roo', 'Cancún', 'Centro'),
  ('Quintana Roo', 'Cancún', 'Zona Hotelera'),
  ('Quintana Roo', 'Cancún', 'Puerto Juárez'),
  ('Quintana Roo', 'Cancún', 'Región 100'),
  ('Quintana Roo', 'Playa del Carmen', 'Centro'),
  ('Quintana Roo', 'Playa del Carmen', 'Playacar'),
  ('Quintana Roo', 'Chetumal', 'Centro'),
  ('Quintana Roo', 'Tulum', 'Centro'),
  ('Quintana Roo', 'Tulum', 'Zona Hotelera'),
  ('San Luis Potosí', 'San Luis Potosí', 'Centro'),
  ('San Luis Potosí', 'San Luis Potosí', 'Lomas'),
  ('San Luis Potosí', 'San Luis Potosí', 'Del Valle'),
  ('San Luis Potosí', 'Soledad de Graciano Sánchez', 'Centro'),
  ('Sinaloa', 'Culiacán', 'Centro'),
  ('Sinaloa', 'Culiacán', 'Las Quintas'),
  ('Sinaloa', 'Culiacán', 'Tres Ríos'),
  ('Sinaloa', 'Mazatlán', 'Centro'),
  ('Sinaloa', 'Mazatlán', 'Zona Dorada'),
  ('Sinaloa', 'Mazatlán', 'Marina Mazatlán'),
  ('Sinaloa', 'Los Mochis', 'Centro'),
  ('Sonora', 'Hermosillo', 'Centro'),
  ('Sonora', 'Hermosillo', 'Pitic'),
  ('Sonora', 'Hermosillo', 'Las Quintas'),
  ('Sonora', 'Ciudad Obregón', 'Centro'),
  ('Sonora', 'Nogales', 'Centro'),
  ('Sonora', 'San Luis Río Colorado', 'Centro'),
  ('Tabasco', 'Villahermosa', 'Centro'),
  ('Tabasco', 'Villahermosa', 'Tabasco 2000'),
  ('Tabasco', 'Villahermosa', 'Carrizal'),
  ('Tabasco', 'Cárdenas', 'Centro'),
  ('Tamaulipas', 'Reynosa', 'Centro'),
  ('Tamaulipas', 'Reynosa', 'Rodríguez'),
  ('Tamaulipas', 'Tampico', 'Centro'),
  ('Tamaulipas', 'Tampico', 'Zona Dorada'),
  ('Tamaulipas', 'Nuevo Laredo', 'Centro'),
  ('Tamaulipas', 'Matamoros', 'Centro'),
  ('Tamaulipas', 'Ciudad Victoria', 'Centro'),
  ('Tlaxcala', 'Tlaxcala', 'Centro'),
  ('Tlaxcala', 'Apizaco', 'Centro'),
  ('Tlaxcala', 'Huamantla', 'Centro'),
  ('Veracruz', 'Veracruz', 'Centro'),
  ('Veracruz', 'Veracruz', 'Boca del Río'),
  ('Veracruz', 'Veracruz', 'Reforma'),
  ('Veracruz', 'Xalapa', 'Centro'),
  ('Veracruz', 'Xalapa', 'Las Ánimas'),
  ('Veracruz', 'Xalapa', 'Zona UV'),
  ('Veracruz', 'Coatzacoalcos', 'Centro'),
  ('Veracruz', 'Córdoba', 'Centro'),
  ('Veracruz', 'Poza Rica', 'Centro'),
  ('Veracruz', 'Orizaba', 'Centro'),
  ('Yucatán', 'Mérida', 'Centro'),
  ('Yucatán', 'Mérida', 'Norte'),
  ('Yucatán', 'Mérida', 'Montejo'),
  ('Yucatán', 'Mérida', 'García Ginerés'),
  ('Yucatán', 'Mérida', 'Itzimná'),
  ('Yucatán', 'Mérida', 'Altabrisa'),
  ('Yucatán', 'Valladolid', 'Centro'),
  ('Yucatán', 'Progreso', 'Centro'),
  ('Yucatán', 'Progreso', 'Zona Malecón'),
  ('Zacatecas', 'Zacatecas', 'Centro'),
  ('Zacatecas', 'Zacatecas', 'Guadalupe'),
  ('Zacatecas', 'Fresnillo', 'Centro')
) as v(estado, ciudad, zona)
join public.ciudades c on c.estado = v.estado and c.ciudad = v.ciudad
on conflict (ciudad_id, zona) do nothing;
